# -*- org -*-
#+TITLE: Being a Journal of my Java Web-App Development Journey
#+COLUMNS: %12TODO %10WHO %3PRIORITY(PRI) %3HOURS(HRS){est+} %85ITEM
# #+INFOJS_OPT: view:showall toc:t ltoc:nil path:../org-info.js mouse:#B3F2E3
# Pandoc needs H:9; default is H:3.
# `^:nil' means raw underscores and carets are not interpreted to mean sub- and superscript.  (Use {} to force interpretation.)
#+OPTIONS: author:nil creator:t H:9 ^:{}
#+HTML_HEAD: <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono:400,400i,600,600i|IBM+Plex+Sans:400,400i,600,600i|IBM+Plex+Serif:400,400i,600,600i">
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/org-mode.css" />

# Generates "up" and "home" links ("." is "current directory").  Can comment one out.
#+HTML_LINK_UP: .
#+HTML_LINK_HOME: /index.html

# Use ``#+ATTR_HTML: :class lower-alpha'' on line before list to use the following class.
# See https://emacs.stackexchange.com/a/18943/17421
# 
#+HTML_HEAD: <style type="text/css">
#+HTML_HEAD:  ol.lower-alpha { list-style-type: lower-alpha; }
#+HTML_HEAD: </style>

* Overview

  I'm going to keep a diary of my effort to develop a web app from soup to nuts.

  The initial plans are in [[file:README.org][README.org]].

* Java

  Currently running my wiki on JSPWiki on Tomcat 8 on Java 8.  I'd like to run a different process
  on Java whatever-is-the-latest.  (Note: I can't.  See [[#jakarta-java-version-question][the Jakarta/Java version question]].

  Looks like some process has kept Java up to date on my AWS server.  Yay.  Also, apparently,
  openjdk is legal to use.  Yay.

  https://adoptopenjdk.net/index.html has the builds for download.

** On a Mac
   
  On a Mac, the OpenJDK 8 installer puts files in
  =/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin=, but I can't seem to
  symlink them in to =/usr/bin=.

** Java EE

   Well, first off, a /lot/ has happened in the Java world since I left it, around 2005 or so.
   (Pshew, was it really that long ago?  Oy.)

   Java EE has become Jakarta EE, and is now managed by the Eclipse Foundation.  It appears that, as
   of <2020-03-09 Mon>, Java EE 8 is the download (from Oracle), but, in future, I guess we'll be
   getting new versions from https://jakarta.ee/.

*** Question: Does Jakarta EE run on any version of Java >= 8?  Answer: apparently not. :(
    :PROPERTIES:
    :CUSTOM_ID: jakarta-java-version-question
    :END:

    Based on this quote: /"We also have to move the APIs to support JDK 11."/ from this article:
    https://dzone.com/articles/jakarta-ee-8-and-beyond. 

* Tomcat

** On a Mac

   Unzipped Tomcat 9 to =/opt=.

   Created user =tomcat= using Mac "Users and Groups" control panel applet.  Disabled login by
   =tomcat= with the following shell command:

   : sudo chpass -s /usr/bin/false tomcat
   
   chown'd the resulting directory (recursively) to user =tomcat=.

   Created a simple =start-tomcat= (and analogous =stop-tomcat=) script in
   =/opt/apache-tomcat-9.0.31/bin= directory:

   #+BEGIN_SRC shell
     #!/bin/bash

     export CATALINA_HOME=/opt/apache-tomcat-9.0.31

     # export CATALINA_BASE=~/Tomcat/apache-tomcat-9.0

     export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home

     exec su -m tomcat ${CATALINA_HOME}/bin/catalina.sh start
   #+END_SRC

   Edited =/opt/apache-tomcat-9.0.31/conf/tomcat-users.xml= to add users for manager-gui, admin-gui
   and (separate user) manager-script, admin-script.

   Running on AdoptOpenJDK 11 is as easy as downloading and installing it and changing the above
   =JAVA_HOME= to point to the new JDK.  It seems to run without problem.

   It should also be possible to install it via homebrew, which might then keep it up to date better than a manual
   install process would.

   For homebrew, you'll need to open a "tap" (i.e., add another repository), and then install the "cask" for the jdk you
   want.  See the instructions at the adoptopenjdk.

** On Ubuntu Linux 16.04

   See http://tarheel-nc.s3-website-us-east-1.amazonaws.com/tomcat-9-setup.html.

** Deploy code

   Well, first you have to write some code.  See [[#hello-world][Simplest possible code]].
   
* Database

** Consider an ORM of some sort


* JavaEE dependencies

  I feel like there's a license restriction on the EE libs from Oracle.  So I need to find an
  implementation I can use.

  Turns out...

  #+BEGIN_QUOTE
  The Apache Tomcat® software is an open source implementation of the Java Servlet, JavaServer
  Pages, Java Expression Language and Java WebSocket technologies. The Java Servlet, JavaServer
  Pages, Java Expression Language and Java WebSocket specifications are developed under the Java
  Community Process.
  #+END_QUOTE

  (From https://tomcat.apache.org/, right at the top.)

  This at least satisfies the compiler:

  : javac -cp /opt/apache-tomcat-9.0.31/lib/servlet-api.jar com/how_hard_can_it_be/play/Main.java

  /I think/ you can also add them via Maven (from
  https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api/4.0.1):

  #+BEGIN_SRC xml
    <!-- https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api -->
    <dependency>
        <groupId>javax.servlet</groupId>
        <artifactId>javax.servlet-api</artifactId>
        <version>4.0.1</version>
        <scope>provided</scope>
    </dependency>
  #+END_SRC 

* JS Framework

* Build system

** Gradle
   
   Gradle is not the clean, well-documented system I had hoped for.  Maybe if this turns into a big,
   giant project, it might pay off, but there seems to be a ton black magic documented in example
   code and (probably) StackOverflow answer, so... maybe just use Maven.

** Maven

   Back to Maven, until I give up on it again.

*** Install/update
    
   Update maven, configure PATH.  (Is that really all I have to do?)  On a Mac.

   Ok, so, I just downloaded the zip from Apache, unzipped it into =/opt= and symlinked the /three/
   executable files in the =bin= directory to =/usr/local/bin=, which is already on the path.

*** Make a project

    

* App code

** Simplest possible code
   :PROPERTIES:
   :CUSTOM_ID: hello-world
   :END:

   Uh...
